config/routes.rb
Zoogbu::Application.routes.draw do

  root :controller=> 'global', :action=>'index'
  

  namespace :admin do
    match '/animal/page/:page_no/sort/:sort_by', :controller=> 'animals', :action=>'index'
    match '/habitat_type/page/:page_no/sort/:sort_by', :controller=> 'habitat_types', :action=>'index'
    match '/status/page/:page_no/sort/:sort_by', :controller=> 'statuses', :action=>'index'
    match '/skill/page/:page_no/sort/:sort_by', :controller=> 'skills', :action=>'index'
    match '/employee/page/:page_no/sort/:sort_by', :controller=> 'employees', :action=>'index'
    match '/maintenance/page/:page_no/sort/:sort_by', :controller=> 'maintenances', :action=>'index'
    match '/food/page/:page_no/sort/:sort_by', :controller=> 'foods', :action=>'index'
    match '/event/page/:page_no/sort/:sort_by', :controller=> 'events', :action=>'index'
    match '/performance/page/:page_no/sort/:sort_by', :controller=> 'performances', :action=>'index'
    match '/subscriber/page/:page_no/sort/:sort_by', :controller=> 'subscribers', :action=>'index'
    match '/buyer/page/:page_no/sort/:sort_by', :controller=> 'buyers', :action=>'index'
    match '/sponsor/page/:page_no/sort/:sort_by', :controller=> 'sponsors', :action=>'index'
    match '/adoption/page/:page_no/sort/:sort_by', :controller=> 'adoptions', :action=>'index'
    match '/sponsorship/page/:page_no/sort/:sort_by', :controller=> 'sponsorships', :action=>'index'
    match '/user/page/:page_no/sort/:sort_by', :controller=> 'users', :action=>'index'
    match '/post/page/:page_no/sort/:sort_by', :controller=> 'posts', :action=>'index'
    match '/comment/page/:page_no/sort/:sort_by', :controller=> 'comments', :action=>'index'
    match '/zoomap/page/:page_no/sort/:sort_by', :controller=> 'zoomaps', :action=>'index'
    match '/map_area/page/:page_no/sort/:sort_by', :controller=> 'map_areas', :action=>'index'

    resources :habitat_types,:habitats, :animals, :statuses, :skills, :employees, 
	:maintenances, :foods, :events, :performances, :subscribers, :buyers, :sponsors, :adoptions, 
	:sponsorships, :users, :posts, :comments, :zoomaps, :map_areas
  end

  match '/admin/:action', :controller=>'admin/admin_main' 
  match '/admin', :controller=> 'admin/admin_main', :action => 'index'

  match '/:action', :controller => 'global'
  match '/index/page/:page_no', :controller=> 'global', :action=>'index'
  match '/zoogle/:action', :controller=> 'global'
  match '/zoogle/:action/:id', :controller=> 'global'
  match '/:action/:event_date', :controller => 'global'
  
  match ':controller/:action/:id'
  match ':controller/:action/:id.:format'

  
end

app/controllers/admin/admin_main_controller.rb
class Admin::AdminMainController < ApplicationController
  layout 'admin'

  before_filter :require_login, :except=> [:login,:authenticating]
  # initialize title to management so that the browsing of #animals, etc will have management_sidebar
  before_filter :init_title

				
				
	
  def login
    @title = "Login"
    redirect_to '/admin' if session[:username]
  end  

  def search
    @title = "Search"
    # if with search string
    if params[:search_string]
		@animals = []
		@employees = []
		@events=[]
		@habitats=[]
		unless params[:search_string].blank?
			ss = '%' + params[:search_string] + '%'

			# search for all animals by its name, description and taxonomy, given the keyword ss
			@animals = Animal.find(:all,:joins=>[:kingdom,:phylum,:aclass,:aorder,:family,:genus,:species,:habitat],
			:conditions=>["animals.gender = ? OR animals.name LIKE ? OR animals.description LIKE ?  OR animals.motto LIKE ?
								OR kingdoms.name LIKE ? OR phylums.name LIKE ? 
								OR aclasses.name LIKE ? OR aorders.name LIKE ? 
								OR families.name LIKE ? OR genus.name LIKE ?
								OR species.name LIKE ? OR habitats.name LIKE ? ",params[:search_string] ,ss,
								ss,ss,ss,ss,ss,ss,ss,ss,ss,ss],:order=>'animals.name')
			@animals += Animal.find(:all, :joins=> [:statuses], :conditions=> ["statuses.name LIKE ?",ss])
			
			#Search for Employees only if HR or admin
			if ["Human Resource", "Administrator"].include? session[:employee_type]
				@employees = Employee.find(:all,:conditions=>["first_name LIKE ? OR  last_name LIKE ? OR middle_name LIKE ? OR employee_type LIKE ? OR
												address LIKE ? OR gender = ?",ss,ss,ss,ss,ss,params[:search_string] ])
				@employees += Employee.find(:all, :joins=> [:events,:skills],
				:conditions=> ["events.name LIKE ? OR skills.name LIKE ?",ss,ss])
			end
			#Search for Events
			@events = Event.find(:all,:conditions=>["name LIKE ? OR  description LIKE ?",ss,ss ])
			@events += Event.find(:all, :joins=> [:habitat],
			:conditions=> ["habitats.name LIKE ? OR habitats.description LIKE ?",ss,ss])
			
			#Search for habitats
			@habitats = Habitat.find(:all,:conditions=>["name LIKE ? OR  description LIKE ?",ss,ss ])
			@habitats += Habitat.find(:all, :joins=> [:habitat_type], :conditions=> ["habitat_types.name LIKE ? OR habitat_types.description LIKE ?",ss,ss])

			#Delete Duplicates
			@employees.uniq!
			@events.uniq!
			@animals.uniq!
			@habitats.uniq!
		end
    else
	    redirect_to '/admin'
    end
  end  


  def logout
    session[:username] = nil
	session[:employee_type] = nil
	flash[:notice] = "Successfully logged out."
    redirect_to '/admin/login'
  end

  def index
    @title = "Summary"
	if session[:username] != "default"
		@user = User.find_by_username(session[:username])
		@user_img_url = @user.employee.img_url ? @user.employee.img_url : "/images/admin/Administrator-icon.png" 
		init_responsibilities
	else
		@user_img_url = "/images/admin/Administrator-icon.png" 
	end
	init_notifications
    
  end

  def management
    @title = "Management"
	if session[:username] != "default"
		@user = User.find_by_username(session[:username])
		@user_img_url = @user.employee.img_url ? @user.employee.img_url : "/images/admin/Administrator-icon.png" 
		init_responsibilities
	else
		@user_img_url = "/images/admin/Administrator-icon.png" 
	end

  end

  def reports
    @title = "Reports"
	init_notifications
	
	@no_active_subs = 0
	@no_cancelled_subs = 0
	@no_pending_subs = 0
	@no_subs = 0
	@no_posts = 0
	@no_active_posts = 0
	@no_employees = 0
	@no_zookeepers = 0
	@no_trainers = 0
	@no_admins = 0
	@no_other_employees = 0
	@no_events = 0 
	@total_visits = 0 
	@no_animals = 0
	@starting_year = Time.now.year 
	@average_annual_growth = 0
	
	#OTHERS
	@no_active_subs = Subscriber.count(:all,:conditions=>["status ='Active'"])
	@no_cancelled_subs = Subscriber.count(:all,:conditions=>["status ='Cancelled'"])
	@no_pending_subs = Subscriber.count(:all,:conditions=>["status ='Pending'"])
	@no_subs = Subscriber.count(:all)
	
	@no_posts = Post.count(:all)
	@no_active_posts = Post.count(:all, :conditions=>["status ='Active'"])
    #EMPLOYEES
	@no_employees = Employee.count(:all)
	@no_zookeepers = Employee.count(:all, :conditions=>["employee_type = 'Zookeeper'"])
	@no_trainers = Employee.count(:all, :conditions=>["employee_type = 'Trainer'"])
	@no_admins = Employee.count(:all, :conditions=>["employee_type = 'Administrator'"])
	@no_other_employees = Employee.count(:all, :conditions=>["employee_type != 'Administrator' AND employee_type != 'Trainer' AND employee_type != 'Zookeeper'"])
	
	
	#EVENTS
	@no_events = Event.count(:all)
	@average_performances = []
	psum = Performance.count(:all, :group => 'event')
	psum.each do |p|
		@average_performances << p[1].to_f
	end
	
	@total_visits = Performance.sum(:no_of_visitors)
	
	
	@average_performances = @average_performances.sum.to_f / @average_performances.size.to_f
	
    #ANIMALS
	@no_animals = Animal.count(:all)
	animal = Animal.find(:first, :order=>"created_at")
	starting_date = animal.created_at
	@starting_year = starting_date.year
	annual_animal_count = []

	while(starting_date.year <= Time.now.year)
		annual_animal_count << Animal.count(:conditions => "created_at <= '#{Date.new(starting_date.year,12,31).to_s(:db)}'")
		starting_date = starting_date.since(1.year) 
	end
	

	annual_growth = [1]

	i = 0

	while(i<annual_animal_count.size-1)
		annual_growth[i] = (annual_animal_count[i+1] - annual_animal_count[i] ).to_f/ annual_animal_count[i].to_f
		i+=1
    end
	@average_annual_growth = annual_growth.sum.to_f / annual_growth.size.to_f
	

  end


  def authenticating
    
	if !params[:username]
	  redirect_to '/admin'
    elsif has_no_admin? && (params[:username] == "default" && params[:password] == "admin")
      session[:username] = "default"
	  session[:employee_type] = "Administrator"
	  flash[:notice] = "Successfully logged in."
      redirect_to '/admin'
    elsif (user = User.find_by_username_and_password(params[:username], Digest::SHA1.hexdigest(params[:password])))
	  session[:username] = user.username
      session[:employee_type] = user.employee.employee_type
	  flash[:notice] = "Successfully logged in."
	  redirect_to '/admin'  
    else
      flash[:notice] = "Invalid username or password."
      redirect_to '/admin/login'
    end
	
  end
  
  


  private
    def require_login
      unless session[:username]
        flash[:notice] = "You must be logged in to access this section."
        redirect_to '/admin/login'
      end
    end
    
    # fail-safe check incase there are no users that are admin
    def has_no_admin?
       if e = Employee.find_by_employee_type("Administrator")
	     if User.find_by_employee_id(e)
		   return false
		 else
		   return true
		 end
	   else 
		 return true
	   end
    end
    
	def init_title
		@title = "Management"
	end
	
 	def init_notifications

		# ANIMAL NOTIFS
		@pregnant_animals = []
		@pregnant_animals += Animal.joins(:statuses).where(:statuses =>{:name => 'Pregnant'})

		@injured_animals = []
		@injured_animals += Animal.joins(:statuses).where(:statuses =>{:name => 'Injured'})

		@new_animals = []
		@new_animals += Animal.find(:all, :conditions=>["animals.created_at >= '#{Time.now.ago(7.days).to_s(:db)}'"])

		@bought_animals = []
		@bought_animals += Animal.joins(:adoption).where(:adoptions => {:created_at => (Time.now.ago(7.days)..Time.now)})

		@sponsored_animals = []
		@sponsored_animals += Animal.joins(:sponsorship).where(:sponsorships => {:created_at => (Time.now.ago(7.days)..Time.now)})


		#EMPLOYEE  NOTIFS
		@new_employees = []
		@new_employees += Employee.find(:all, :conditions=>["employees.created_at >= '#{Time.now.ago(7.days).to_s(:db)}'"])

		@bday_employees = []
		@bday_employees += Employee.where(:birthdate => Date.today)
		
		#EVENTS
		@new_events = []
		@new_events += Event.find(:all, :conditions=>["events.created_at >= '#{Time.now.ago(7.days).to_s(:db)}'"])
		
		@upcoming_performances = []
		@upcoming_performances += Performance.find(:all, :conditions=>["event_date >= '#{Date.today.beginning_of_month.to_s(:db)}' AND event_date <='#{Date.today.end_of_month.to_s(:db)}'"],:order=>'event_date ASC')
		
		#OTHER
		@pending_subscriptions = []
		@pending_subscriptions = Subscriber.find(:all, :conditions=>["status = 'Pending'"])
		
		@active_posts = []
		@active_posts = Post.find(:all,:conditions=>["status = 'Pending'"])
		
		@new_comments = []
		@new_comments = Comment.find(:all, :conditions=>["created_at >= '#{Time.now.ago(7.days).to_s(:db)}'"])

	end    
    
	def init_responsibilities()
		if session[:employee_type] == "Trainer"
			@events = []
			@events += @user.employee.events
		elsif session[:employee_type] == "Zookeeper"
			@maintenances = []
			@maintenances += @user.employee.maintenances
		end
	end


end

app/helpers/admin_main_helper.rb
module AdminMainHelper
 def process_file_uploader
  #validates_file_format_of :img_upload, 
	#					   :in=>["gif", "jpg", "jpeg", "png", "bmp", "tif", "tiff","pcx", "tga", "svg", "ico"],
	#					   :message=>"Sorry. Invalid image file"

   if img_upload
     unless img_upload.class === "String"
	 dest = File.open("#{::Rails.root.to_s}/public/images/data/#{img_upload.original_filename}", 'wb')
	 dest.write(img_upload.read)
       self.img_url = "/images/data/#{img_upload.original_filename}" 
     end 
   end
  end
end

app/views/admin/admin_main/_management_sidebar.erb
<% controller_name = params[:controller]%>

<div id="sidebar">

	<ul id="MenuBar1" class="MenuBarVertical">
            <li><h3>Management</h3></li>
   			<% if session[:employee_type] == "Zookeeper" || session[:employee_type] == "Administrator"%>

				<li<%= " class=current_page_item" if controller_name=="admin/animals" %>><a class="MenuBarItemSubmenu" href="#"><img src="/images/admin/Mammooth-icon.png">Animals</a>
					 <ul>
						<li><%= link_to "Create Animals", new_admin_animal_path %> </li>
						<li><%= link_to "Browse Animals", admin_animals_path %> </li>
					 </ul>
				</li>


				<li<%= " class=current_page_item" if controller_name=="admin/statuses" %> ><a class="MenuBarItemSubmenu" href="#"><img src="/images/admin/syringe-icon.png">Statuses</a>
					 <ul>
						<li><%= link_to "Create Statuses", new_admin_status_path %> </li>
						<li><%= link_to "Browse Statuses", admin_statuses_path %> </li>
					 </ul>
				</li>
			
			
				<li<%= " class=current_page_item" if controller_name=="admin/maintenances" %> ><a href="#"><img src="/images/admin/equipment_icon.png">Maintenances</a>
				  <ul>
					<li><%= link_to "Create Maintenance", new_admin_maintenance_path %></li>
					<li><%= link_to "Browse Maintenances", admin_maintenances_path %></li>
				  </ul>
				</li>


				<li<%= " class=current_page_item" if controller_name=="admin/foods" %> ><a href="#"><img src="/images/admin/meat-icon.png">Foods</a>
				  <ul>
					<li><%= link_to "Create Foods", new_admin_food_path %></li>
					<li><%= link_to "Browse Foods", admin_foods_path %></li>
				  </ul>
				</li>
			
			<% end %>

			
			<% if session[:employee_type] == "Trainer" || session[:employee_type] == "Administrator"%>
				<li<%= " class=current_page_item" if controller_name=="admin/events" %> ><a href="#"><img src="/images/admin/event_icon.png">Events</a>
				  <ul>
					<li><%= link_to "Create Events", new_admin_event_path %></li>
					<li><%= link_to "Browse Events", admin_events_path %></li>
				  </ul>
				</li>		 


				<li<%= " class=current_page_item" if controller_name=="admin/performances" %> ><a href="#"><img src="/images/admin/Ringmaster-icon.png">Performances</a>
				  <ul>
					<li><%= link_to "Create Performances", new_admin_performance_path %></li>
					<li><%= link_to "Browse Performances", admin_performances_path %></li>
				  </ul>
				</li>
			<% end %>
			
			
			
				
		    
			
			<% if session[:employee_type] == "Human Resource" || session[:employee_type] == "Administrator"%>
				<li<%= " class=current_page_item" if controller_name=="admin/employees" %> ><a href="#"><img src="/images/admin/User-Preppy-Green-icon.png">Employees</a>
				  <ul>
					<li><%= link_to "Create Employees", new_admin_employee_path %></li>
					<li><%= link_to "Browse Employees", admin_employees_path %></li>
				  </ul>
				</li>

				
				<li<%= " class=current_page_item" if controller_name=="admin/skills" %> ><a class="MenuBarItemSubmenu" href="#"><img src="/images/admin/Preppy-icon.png">Skills</a>
					 <ul>
						<li><%= link_to "Create Skills", new_admin_skill_path %> </li>
						<li><%= link_to "Browse Skills", admin_skills_path %> </li>
					 </ul>
				</li>
				
				<li<%= " class=current_page_item" if controller_name=="admin/subscribers" %> ><a href="#"><img src="/images/admin/contract-icon.png">Subscribers</a>
					<ul>
						<li><%= link_to "Create Subscribers", new_admin_subscriber_path %></li>
						<li><%= link_to "Browse Subscribers", admin_subscribers_path %></li>
					</ul>
				</li>

				<li<%= " class=current_page_item" if controller_name=="admin/buyers" %> ><a href="#"><img src="/images/admin/buyer-icon.png">Buyers</a>
				  <ul>
					<li><%= link_to "Create Buyers", new_admin_buyer_path %></li>
					<li><%= link_to "Browse Buyers", admin_buyers_path %></li>
				  </ul>
				</li>

				<li<%= " class=current_page_item" if controller_name=="admin/adoptions" %> ><a href="#"><img src="/images/admin/cat-icon.png">Adoptions</a>
				  <ul>
					<li><%= link_to "Create Adoptions", new_admin_adoption_path %></li>
					<li><%= link_to "Browse Adoptions", admin_adoptions_path %></li>
				  </ul>
				</li>

				<li<%= " class=current_page_item" if controller_name=="admin/sponsorships" %> ><a href="#"><img src="/images/admin/spons-icon.png">Sponsorships</a>
				  <ul>
					<li><%= link_to "Create Sponsorships", new_admin_sponsorship_path %></li>
					<li><%= link_to "Browse Sponsorships", admin_sponsorships_path %></li>
				  </ul>
				</li>

				<li<%= " class=current_page_item" if controller_name=="admin/sponsors" %> ><a href="#"><img src="/images/admin/User-Preppy-Blue-icon.png">Sponsors</a>
				  <ul>
					<li><%= link_to "Create Sponsors", new_admin_sponsor_path %></li>
					<li><%= link_to "Browse Sponsors", admin_sponsors_path %></li>
				  </ul>
				</li>
			<% end %>
			
			<% if session[:employee_type] == "Administrator"%>
			
				<li<%= " class=current_page_item" if controller_name=="admin/posts" %> ><a class="MenuBarItemSubmenu" href="#" ><img src="/images/admin/blog-post-edit-icon.png" />Posts</a>
				  <ul>
					<li><%= link_to "Create Posts", new_admin_post_path %> </li>
					<li><%= link_to "Browse Posts", admin_posts_path %></li>
				  </ul>
				</li>
				
				<li<%= " class=current_page_item" if controller_name=="admin/comments" %> ><a class="MenuBarItemSubmenu" href="#" ><img src="/images/admin/Text-Bubble-icon.png" />Comments</a>
				  <ul>
					<li><%= link_to "Create Comments", new_admin_comment_path %> </li>
					<li><%= link_to "Browse Comments", admin_comments_path %></li>
				  </ul>
				</li>
			
				<li<%= " class=current_page_item" if controller_name=="admin/habitat_types" %> ><a class="MenuBarItemSubmenu" href="#" ><img src="/images/admin/Habitat.png" />Habitat Types</a>
				  <ul>
					<li><%= link_to "Create Habitat Types", new_admin_habitat_type_path %> </li>
					<li><%= link_to "Browse Habitat Types", admin_habitat_types_path %></li>
				  </ul>
				</li>

				<li<%= " class=current_page_item" if controller_name=="admin/habitats" %> ><a class="MenuBarItemSubmenu" href="#" ><img src="/images/admin/Habitat-icon.png" />Habitat</a>
				  <ul>
					<li><%= link_to "Create Habitats", new_admin_habitat_path %></li>
					<li><%= link_to "Browse Habitats", admin_habitats_path %></li>
				  </ul>
				</li>
				
				<li<%= " class=current_page_item" if controller_name=="admin/zoomaps" %> ><a class="MenuBarItemSubmenu" href="#" ><img src="/images/admin/System-Map-icon.png" />Zoomap</a>
				  <ul>
					<li><%= link_to "Create Zoomap", new_admin_zoomap_path %></li>
					<li><%= link_to "Browse Zoomaps", admin_zoomaps_path %></li>
				  </ul>
				</li>
				
				<li<%= " class=current_page_item" if controller_name=="admin/map_areas" %> ><a class="MenuBarItemSubmenu" href="#" ><img src="/images/admin/System-Map-icon2.png" />Map Area</a>
				  <ul>
					<li><%= link_to "Create Map Area", new_admin_map_area_path %></li>
					<li><%= link_to "Browse Map Areas", admin_map_areas_path %></li>
				  </ul>
				</li>				

			
				<li<%= " class=current_page_item" if controller_name=="admin/users" %> ><a href="#"><img src="/images/admin/User-Preppy-Red-icon.png">Users</a>
				  <ul>
					<li><%= link_to "Create Users", new_admin_user_path %></li>
					<li><%= link_to "Browse Users", admin_users_path %></li>
				  </ul>
				</li>
				
				
			<% end %>
			
			


	</ul>
 
 </div>

app/views/admin/admin_main/_summary_sidebar.erb
<% controller_name = params[:controller]%>

<div id="sidebar">
	<ul id="MenuBar1" class="MenuBarVertical">
	<% unless @pregnant_animals.empty? && @injured_animals.empty? && @sponsored_animals.empty? && @new_animals.empty? && @bought_animals.empty?  %>
            <li><h3><font size=3>Animal Notifications<font></h3></li>	
				<% unless @pregnant_animals.empty? %>
				<li><a><img src="/images/admin/baby-cot-icon.png" /><%= @pregnant_animals.size %> Pregnant</a>
				  <ul>
					<li><h3>Pregnant</h3></li>
					<% @pregnant_animals.each do |a| %>
					<li><%= link_to a.name, admin_animal_path(a) %> </li>
					<% end %>
				  </ul>
				</li>
				<%end%>
				<% unless @injured_animals.empty? %>
				<li><a><img src="/images/admin/plaster-icon.png" /><%= @injured_animals.size%> Injured</a>
				  <ul>
					<li><h3>Injured</h3></li>
					<% @injured_animals.each do |a| %>
					<li><%= link_to a.name, admin_animal_path(a) %> </li>
					<% end %>
				  </ul>
				</li>
				<%end%>
				<% unless @new_animals.empty? %>
				<li><a><img src="/images/admin/Add-icon.png" /><%= @new_animals.size%> New</a>
				  <ul>
					<li><h3>New</h3></li>
					<% @new_animals.each do |a| %>
					<li><%= link_to a.name, admin_animal_path(a) %> </li>
					<% end %>
				  </ul>
				</li>
				<%end%>
				<% unless @bought_animals.empty? %>
				<li><a class="MenuBarItemSubmenu" href="#" ><img src="/images/admin/cat-icon.png" /><%= @bought_animals.size%> Adopted</a>
				  <ul>
					<li><h3>Newly Bought</h3></li>
					<% @bought_animals.each do |a| %>
					<li><%= link_to a.name, admin_animal_path(a) %> </li>
					<% end %>
				  </ul>
				</li>
				<%end%>
				<% unless @sponsored_animals.empty? %>
				<li><a class="MenuBarItemSubmenu" href="#" ><img src="/images/admin/spons-Icon.png" /><%= @sponsored_animals.size%> Sponsored</a>
				  <ul>
					<li><h3>Newly Donated</h3></li>
					<% @sponsored_animals.each do |a| %>
					<li><%= link_to a.name, admin_animal_path(a) %> </li>
					<% end %>
				  </ul>
				</li>
				<%end%>
	<%end%>
	<br/>
	
	<% unless @new_employees.empty? && @bday_employees.empty?%>
            <li><h3>Employee Updates</h3></li>			
				<% unless @new_employees.empty? %>
				<li><a><img src="/images/admin/Add-User-icon.png" /><%= @new_employees.size%> New</a>
				  <ul>
					<li><h3>New</h3></li>
					<% @new_employees.each do |a| %>
					<li><%= link_to a.complete_name, admin_employee_path(a) %> </li>
					<% end %>
				  </ul>
				</li>
				<%end%>
				<% unless 	@bday_employees.empty? %>
				<li><a><img src="/images/admin/Cake-icon.png" /><%= @bday_employees.size%> Birthday</a>
				  <ul>
					<li><h3>Celebrants</h3></li>
					<% @bday_employees.each do |a| %>
					<li><%= link_to a.complete_name, admin_employee_path(a) %> </li>
					<% end %>
				  </ul>
				</li>
			<% end %>
	<%end%>
		<br/>
		
		
		<% unless @new_events.empty? && @upcoming_performances.empty? %>
	        <li><h3>Event Updates</h3></li>			
				<% unless @upcoming_performances.empty? %>
				<li><a><img src="/images/admin/event_icon.png" /><%= @upcoming_performances.size%> Monthly Performances</a>
				  <ul>
					<li><h3>events</h3></li>
					<% @upcoming_performances.each do |a| %>
					<li><%= link_to a.event.name, admin_performance_path(a) %> </li>
					<% end %>
				  </ul>
				</li>
				<% end %>
				
			<% unless @new_events.empty? %>
			<li><a><img src="/images/admin/event_icon.png" /><%= @new_events.size%> New</a>
				  <ul>
					<li><h3>New</h3></li>
					<% @new_events.each do |a| %>
					<li><%= link_to a.name, admin_event_path(a) %> </li>
					<% end %>
				  </ul>
				</li>
			<% end %>
		<br/>
		<% end %>

	<% unless @pending_subscriptions.empty? && @active_posts.empty? && @new_comments.empty?%>	
            <li><h3>OTHER Updates</h3></li>			
				<% unless @pending_subscriptions.empty? %>
				<li><%= link_to image_tag("/images/admin/Contract-icon.png")+@pending_subscriptions.size.to_s+" Pending Subscriptions", admin_subscribers_path %></li>
				<% end %>
				
				<% unless @active_posts.empty? %>
				<li><%= link_to image_tag("/images/admin/blog-post-edit-icon.png")+@active_posts.size.to_s+" Pending Posts", admin_posts_path %></li>
				<% end %>
				
				<% unless @new_comments.empty? %>
				<li>
					<%= link_to image_tag("/images/admin/Text-Bubble-icon.png")+@new_comments.size.to_s+" New Comments", admin_comments_path %>
					<ul>
						<li><h3>New</h3></li>
						<% @new_comments.each do |a| %>
						<li><%= link_to a.post.title, admin_comment_path(a) %> </li>
						<% end %>
					</ul>
			
				</li>
				<% end %>
	<%end%>
    <% if @pregnant_animals.empty? && @injured_animals.empty? && @sponsored_animals.empty? && @new_animals.empty? && @bought_animals.empty? && @pending_subscriptions.empty? && @active_posts.empty? && @new_comments.empty? && @new_events.empty? && @upcoming_performances.empty? &&  @new_employees.empty? && @bday_employees.empty?%>	
	           <li><h3>NO UPDATES</h3></li>			
				<li><a><img src="/images/admin/Delete-icon.png" /></a></li>
	<%end%>
	</ul>
 
 </div>

app/views/admin/admin_main/index.html.erb
        	
			<%= render :partial=>'summary_index'%>
			
			

app/views/admin/admin_main/management.html.erb
<%= render :partial=>'summary_index' %>