config/routes.rb
Zoogbu::Application.routes.draw do

  root :controller=> 'global', :action=>'index'
  

  namespace :admin do
    match '/animal/page/:page_no/sort/:sort_by', :controller=> 'animals', :action=>'index'
    match '/habitat_type/page/:page_no/sort/:sort_by', :controller=> 'habitat_types', :action=>'index'
    match '/status/page/:page_no/sort/:sort_by', :controller=> 'statuses', :action=>'index'
    match '/skill/page/:page_no/sort/:sort_by', :controller=> 'skills', :action=>'index'
    match '/employee/page/:page_no/sort/:sort_by', :controller=> 'employees', :action=>'index'
    match '/maintenance/page/:page_no/sort/:sort_by', :controller=> 'maintenances', :action=>'index'
    match '/food/page/:page_no/sort/:sort_by', :controller=> 'foods', :action=>'index'
    match '/event/page/:page_no/sort/:sort_by', :controller=> 'events', :action=>'index'
    match '/performance/page/:page_no/sort/:sort_by', :controller=> 'performances', :action=>'index'
    match '/subscriber/page/:page_no/sort/:sort_by', :controller=> 'subscribers', :action=>'index'
    match '/buyer/page/:page_no/sort/:sort_by', :controller=> 'buyers', :action=>'index'
    match '/sponsor/page/:page_no/sort/:sort_by', :controller=> 'sponsors', :action=>'index'
    match '/adoption/page/:page_no/sort/:sort_by', :controller=> 'adoptions', :action=>'index'
    match '/sponsorship/page/:page_no/sort/:sort_by', :controller=> 'sponsorships', :action=>'index'
    match '/user/page/:page_no/sort/:sort_by', :controller=> 'users', :action=>'index'
    match '/post/page/:page_no/sort/:sort_by', :controller=> 'posts', :action=>'index'
    match '/comment/page/:page_no/sort/:sort_by', :controller=> 'comments', :action=>'index'
    match '/zoomap/page/:page_no/sort/:sort_by', :controller=> 'zoomaps', :action=>'index'
    match '/map_area/page/:page_no/sort/:sort_by', :controller=> 'map_areas', :action=>'index'

    resources :habitat_types,:habitats, :animals, :statuses, :skills, :employees, 
	:maintenances, :foods, :events, :performances, :subscribers, :buyers, :sponsors, :adoptions, 
	:sponsorships, :users, :posts, :comments, :zoomaps, :map_areas
  end

  match '/admin/:action', :controller=>'admin/admin_main' 
  match '/admin', :controller=> 'admin/admin_main', :action => 'index'

  match '/:action', :controller => 'global'
  match '/index/page/:page_no', :controller=> 'global', :action=>'index'
  match '/zoogle/:action', :controller=> 'global'
  match '/zoogle/:action/:id', :controller=> 'global'
  match '/:action/:event_date', :controller => 'global'
  
  match ':controller/:action/:id'
  match ':controller/:action/:id.:format'

  
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :habitat
  
  has_and_belongs_to_many :employees
  has_and_belongs_to_many :animals
  
  has_many :performances, :dependent=>:destroy
    
  validates_uniqueness_of :name
  validates_presence_of :name, :capacity, :habitat_id
  validates_numericality_of :capacity, :only_integer=>true
  	   
  


end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminMainController

  before_filter :require_trainer, :except=>[:index, :show]
  def index
    # pagination logic
	# count events
	event_count = Event.count
	
	@no_of_pages = (event_count % 10)== 0 ? event_count/10 : (event_count/10) + 1
	
	@current_page = params[:page_no] ? params[:page_no].to_i : 1
	
	@sort_by = params[:sort_by] ? params[:sort_by] : "id"
	
	
	@events = Event.find(:all, :offset =>(@current_page-1) * 10, :limit=> 10, :order=>"#{@sort_by}")
  end

  def show
    @event = Event.find(params[:id])
  end
  
  def new
    @event = Event.new
    
  end

  def create	
    @event = Event.new(params[:event])

    if @event.save
      flash[:notice] = "Added new event."
      redirect_to admin_event_path(@event)
      
    else
      flash[:notice] = "Failed saving new event."
      render :action => "new"
    end
    
    
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    params[:event][:employee_ids] ||= []
    params[:event][:animal_ids] ||= []
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      flash[:notice] = "Updated event."
      redirect_to admin_event_path(@event)
      
    else
      flash[:notice] = "Failed updating event."
      render :action => "edit"
    end

  end

  def destroy
    @event = Event.find(params[:id])
    if @event.destroy
      flash[:notice] = "Deleted event."
      
    else
      flash[:notice] = "Failed deleting event."
    end
    redirect_to admin_events_path
  end

  private
    def require_trainer
		unless ["Trainer","Administrator"].include? session[:employee_type]
			flash[:notice] = "Unauthorized access."
			redirect_to '/admin/management'
		end
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_animals.html.erb
<h2>Animals participating:</h2>
<ul>
   <% event.animals.each do |a| %>
   <li><%= link_to a.name, admin_animal_path(a) %></li>
   <% end %>
</ul>

app/views/admin/events/_form.erb
<%= form_for([:admin,@event]) do |f|%>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<p>
<%= f.label "Event location:" %></br> 
<%= f.collection_select :habitat_id, Habitat.find(:all, :order=>"name"), :id, :name, :prompt =>"Select a Habitat"%>
</p>


<p>
<%= f.label "Name:"%> </br> 
<%= f.text_field :name %>
</p>


<p>
<%= f.label "Description:"%> </br> 
<%= f.text_area :description %>
</p>


<p>
<%= f.label "Capacity:"%> </br> 
<%= f.text_field :capacity %>
</p>

<p>
<%= f.label "Img URL:"%> </br> 
<%= f.text_field :img_url %>
</p>

<p>
<%= f.label "Img Description:"%> </br> 
<%= f.text_area :img_description %>
</p>







<p> 
<h2> Assign to trainers: </h2> 
<ul>
<% Employee.find_all_by_employee_type("Trainer", :order=>"last_name").each do |t| %>
   <li>
	   <%= check_box_tag "event[employee_ids][]", t.id, @event.employees.include?(t) %>
	   <%=h t.last_name %> , <%=h t.first_name %>
   </li>
<% end %>
</ul>
</p>


<p> 
<h2> Participating Animals: </h2> 
<ul>
<% Animal.find(:all, :order=>"name").each do |a| %>
   <li>
	   <%= check_box_tag "event[animal_ids][]", a.id, @event.animals.include?(a) %>
	   <%= link_to h(a.name), admin_animal_path(a) %> -- <%=h a.scientific_name %>
   </li>
<% end %>
</ul>
</p>

<p>
<%= f.submit button%>
</p>
<%end%>

app/views/admin/events/_list.html.erb
<table border="2" align="center" >
<tr class="table_head"><td><b><%= link_to "ID", "/admin/event/page/#{@current_page}/sort/id" %></b></td>
    <td><b><%= link_to "NAME", "/admin/event/page/#{@current_page}/sort/name" %></b></td>
    <td><b>HABITAT</b></td>
    <td><b>OPERATIONS</b></td>
</tr>
<% @events.each do |e| %>
<tr>
<td><%=e.id %></td>
<td><%= e.name%></td>
<td><%=e.habitat.name %></td>
<td>	<%= link_to "Show", admin_event_path(e) %>
	<%= link_to "Edit", edit_admin_event_path(e) %>
	<%= link_to "Delete", admin_event_path(e), :confirm=>"Are you sure?",:method=>'delete' %>
</td>
</tr>
  <% end %>
</table>

app/views/admin/events/_trainers.html.erb
<h2>Assigned Employees:</h2>
<ul>
   <% event.employees.each do |e| %>
   <li><%= link_to e.last_name+", "+e.first_name, admin_employee_path(e) %></li>
   <% end %>
</ul>

app/views/admin/events/edit.html.erb
<h1>Edit Event</h1>

<%= render :partial=>'form', :locals=>{:button=>'Update'}%>

app/views/admin/events/index.html.erb
<h1>Events</h1>
<div class="post">
  <%= render :partial => 'list' %>
<%= link_to "New Event", new_admin_event_path %>


<% if @current_page > 1 %>
	<%= link_to "back", "/admin/event/page/#{@current_page-1}/sort/#{@sort_by}" %>
<% end %>

<% @no_of_pages.times do |page|%>
	<% unless page+1 == @current_page %>
		<%= link_to page+1, "/admin/event/page/#{page+1}/sort/#{@sort_by}" %>
	<% else %>
		<%= page+1 %>
	<% end %>
<% end %>

<% if @current_page < @no_of_pages %>
	<%= link_to "next", "/admin/event/page/#{@current_page+1}/sort/#{@sort_by}" %>
<% end %>

</div>

app/views/admin/events/new.html.erb
<h1>New Event</h1>

<%= render :partial=>'form', :locals=>{:button=>'Create'}%>

app/views/admin/events/show.html.erb
<h1>
<%=h@event.name%><font size=2>&nbsp;[<%= link_to "Edit", edit_admin_event_path(@event) %>]</font></h1>

<div class="post">
<table id="shows" align="center">
<tr>
	<td rowspan="6" width="400" height="300" align="center">

<% if @event.img_url.blank?%>
	<img src="/images/data/noimage.jpg" alt="NO IMAGE AVAILABLE" width="400"; height=auto; />
<% else %>
	<img src="<%= @event.img_url%>" alt="<%=h@event.img_description%>"  width="400"; height=auto />
<% end %>

	</td>
<tr>

<tr><td width="100">Event Name: </td>
<td><%=h@event.name%></td>
</tr>

<tr><td>Capacity: </td> 
<td><%= @event.capacity%></td>
</tr>

<tr><td>Event Location: </td> 
<td><%= link_to @event.habitat.name, admin_habitat_path(@event.habitat) %></td>
</tr>

<tr>
<td colspan="2"><%=h @event.description %></td>
</tr>
</table>





<%= render :partial=> 'trainers', :locals => {:event => @event} %>
<%= render :partial=> 'animals', :locals => {:event => @event} %>