config/routes.rb
Zoogbu::Application.routes.draw do

  root :controller=> 'global', :action=>'index'
  

  namespace :admin do
    match '/animal/page/:page_no/sort/:sort_by', :controller=> 'animals', :action=>'index'
    match '/habitat_type/page/:page_no/sort/:sort_by', :controller=> 'habitat_types', :action=>'index'
    match '/status/page/:page_no/sort/:sort_by', :controller=> 'statuses', :action=>'index'
    match '/skill/page/:page_no/sort/:sort_by', :controller=> 'skills', :action=>'index'
    match '/employee/page/:page_no/sort/:sort_by', :controller=> 'employees', :action=>'index'
    match '/maintenance/page/:page_no/sort/:sort_by', :controller=> 'maintenances', :action=>'index'
    match '/food/page/:page_no/sort/:sort_by', :controller=> 'foods', :action=>'index'
    match '/event/page/:page_no/sort/:sort_by', :controller=> 'events', :action=>'index'
    match '/performance/page/:page_no/sort/:sort_by', :controller=> 'performances', :action=>'index'
    match '/subscriber/page/:page_no/sort/:sort_by', :controller=> 'subscribers', :action=>'index'
    match '/buyer/page/:page_no/sort/:sort_by', :controller=> 'buyers', :action=>'index'
    match '/sponsor/page/:page_no/sort/:sort_by', :controller=> 'sponsors', :action=>'index'
    match '/adoption/page/:page_no/sort/:sort_by', :controller=> 'adoptions', :action=>'index'
    match '/sponsorship/page/:page_no/sort/:sort_by', :controller=> 'sponsorships', :action=>'index'
    match '/user/page/:page_no/sort/:sort_by', :controller=> 'users', :action=>'index'
    match '/post/page/:page_no/sort/:sort_by', :controller=> 'posts', :action=>'index'
    match '/comment/page/:page_no/sort/:sort_by', :controller=> 'comments', :action=>'index'
    match '/zoomap/page/:page_no/sort/:sort_by', :controller=> 'zoomaps', :action=>'index'
    match '/map_area/page/:page_no/sort/:sort_by', :controller=> 'map_areas', :action=>'index'

    resources :habitat_types,:habitats, :animals, :statuses, :skills, :employees, 
	:maintenances, :foods, :events, :performances, :subscribers, :buyers, :sponsors, :adoptions, 
	:sponsorships, :users, :posts, :comments, :zoomaps, :map_areas
  end

  match '/admin/:action', :controller=>'admin/admin_main' 
  match '/admin', :controller=> 'admin/admin_main', :action => 'index'

  match '/:action', :controller => 'global'
  match '/index/page/:page_no', :controller=> 'global', :action=>'index'
  match '/zoogle/:action', :controller=> 'global'
  match '/zoogle/:action/:id', :controller=> 'global'
  match '/:action/:event_date', :controller => 'global'
  
  match ':controller/:action/:id'
  match ':controller/:action/:id.:format'

  
end

app/models/adoption.rb
class Adoption < ActiveRecord::Base
  belongs_to :animal
  belongs_to :buyer
  
  validates_presence_of :animal_id, :buyer_id, :delivery_address, :payment_mode
  validates_uniqueness_of :animal_id
end

app/controllers/admin/adoptions_controller.rb
class Admin::AdoptionsController < Admin::AdminMainController

  before_filter :require_human_resource

  def index
    # pagination logic
	# count adoptions
	adoption_count = Adoption.count
	
	@no_of_pages = (adoption_count % 10)== 0 ? adoption_count/10 : (adoption_count/10) + 1
	
	@current_page = params[:page_no] ? params[:page_no].to_i : 1
	
	@sort_by = params[:sort_by] ? params[:sort_by] : "id"
	
	@adoptions = Adoption.find(:all, :offset =>(@current_page-1) * 10, :limit=> 10, :order=>"#{@sort_by}")
	
  end

  def show
    @adoption = Adoption.find(params[:id])
  end
  
  def new
    @adoption = Adoption.new
  end

  def create
    @adoption = Adoption.new(params[:adoption])
    if @adoption.save
      flash[:notice] = "Added new adoption."
      redirect_to admin_adoption_path(@adoption)
      
    else
      flash[:notice] = "Failed saving new adoption."
      render :action => "new"
    end
    
    
  end

  def edit
    @adoption = Adoption.find(params[:id])
  end

  def update
    @adoption = Adoption.find(params[:id])
    if @adoption.update_attributes(params[:adoption])
      flash[:notice] = "Updated adoption."
      redirect_to admin_adoption_path(@adoption)
      
    else
      flash[:notice] = "Failed updating adoption."
      render :action => "edit"
    end

  end

  def destroy
    @adoption = Adoption.find(params[:id])
    if @adoption.destroy
      flash[:notice] = "Deleted adoption."
      
    else
      flash[:notice] = "Failed deleting adoption."
    end
    redirect_to admin_adoptions_path
  end
  
  private
    def require_human_resource
		unless ["Human Resource", "Administrator"].include? session[:employee_type]
			flash[:notice] = "Unauthorized access."
			redirect_to '/admin/management'
		end		
	end


end

app/helpers/adoptions_helper.rb
module AdoptionsHelper
end

app/views/admin/adoptions/_form.erb
<%= form_for([:admin,@adoption]) do |f|%>
  <% if @adoption.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adoption.errors.count, "error") %> prohibited this adoption from being saved:</h2>

      <ul>
      <% @adoption.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<p>
<%= f.label "Animal:" %></br> 
<%= f.collection_select :animal_id, Animal.find_by_sql("SELECT ANIMALS.* FROM ANIMALS LEFT OUTER JOIN ADOPTIONS ON ANIMALS.ID = ADOPTIONS.ANIMAL_ID WHERE BUYER_ID IS NULL ORDER BY ANIMALS.NAME") , :id, :name, :prompt =>"Select an animal" %>
</p>


<p>
<%= f.label "Buyer:" %></br> 
<%= f.collection_select :buyer_id, Buyer.find(:all, :conditions=> "status = 'Active'"), :id, :name, :prompt =>"Select a buyer" %>
</p>




<p>
<%= f.label "Purchase date:" %></br> 
<%= f.date_select :purchase_date %>
</p>


<p>
<%= f.label "Delivery address:" %></br>
<%= f.text_area :delivery_address %>
</p>


<p>
<%= f.label "Payment mode:" %></br>
<%= f.radio_button(:payment_mode, "Zookeeper") %> <%= f.label "Cash" %></br> 
<%= f.radio_button(:payment_mode, "Trainer") %> <%= f.label "Check" %></br>
</p>

<p>
<%= f.submit button%>
</p>

<% end %>

app/views/admin/adoptions/_list.html.erb
<table border="2" align="center" >
<tr class="table_head"><td><b><%= link_to "ID", "/admin/adoption/page/#{@current_page}/sort/id" %></b></td>
    <td><b>ANIMAL NAME</b></td>
    <td><b>BUYER NAME</b></td>
    <td><b>OPERATIONS</b></td>
</tr>
<% @adoptions.each do |a| %>
<tr>
<td><%=a.id %></td>
<td><%= a.buyer.name %></td>
<td><%= a.animal.name %> </td>
<td>	<%= link_to "Show", admin_adoption_path(a) %>
	<%= link_to "Edit", edit_admin_adoption_path(a) %>
	<%= link_to "Delete", admin_adoption_path(a), :confirm=>"Are you sure?",:method=>'delete' %>
</td>
</tr>
  <% end %>
</table>

app/views/admin/adoptions/edit.html.erb
<h1>Edit Adoption</h1>


<%= render :partial=>'form', :locals=>{:button=>'Update'}%>

app/views/admin/adoptions/index.html.erb
<h1>Adoptions</h1>
<div class="post">
  <%= render :partial => 'list' %>
<%= link_to "New Adoption", new_admin_adoption_path %>

<% if @current_page > 1 %>
	<%= link_to "back", "/admin/adoption/page/#{@current_page-1}/sort/#{@sort_by}" %>
<% end %>

<% @no_of_pages.times do |page|%>
	<% unless page+1 == @current_page %>
		<%= link_to page+1, "/admin/adoption/page/#{page+1}/sort/#{@sort_by}" %>
	<% else %>
		<%= page+1 %>
	<% end %>
<% end %>

<% if @current_page < @no_of_pages %>
	<%= link_to "next", "/admin/adoption/page/#{@current_page+1}/sort/#{@sort_by}" %>
<% end %>



</div>

app/views/admin/adoptions/new.html.erb
<h1>New Adoption</h1>


<%= render :partial=>'form', :locals=>{:button=>'Create'}%>

app/views/admin/adoptions/show.html.erb
<h1>
<%=h @adoption.buyer.name%> - <%=h @adoption.animal.name%><font size=2>&nbsp;[<%= link_to "Edit", edit_admin_adoption_path(@adoption) %>]</font></h1>

<div class="post">
<table id="shows" align="center">

<tr>
<td width="125">Adoption date:</td>
<td><%= @adoption.purchase_date.strftime("%B %d, %Y, %A") %></td>
</tr>

<tr><td>Delivery address: </td>
<td><%=h @adoption.delivery_address%></td>
</tr>


<tr>
<td>Payment mode: </td> 
<td><%=h @adoption.payment_mode%></td>
</tr>


<tr><td>Animal: </td> 
<td><%= link_to h(@adoption.animal.name), admin_animal_path(@adoption.animal) %></td>
</tr>


<tr><td>Buyer:</td>
<td><%= link_to h(@adoption.buyer.name), admin_buyer_path(@adoption.buyer) %></td>
</tr>

</table>
</div>