config/routes.rb
Zoogbu::Application.routes.draw do

  root :controller=> 'global', :action=>'index'
  

  namespace :admin do
    match '/animal/page/:page_no/sort/:sort_by', :controller=> 'animals', :action=>'index'
    match '/habitat_type/page/:page_no/sort/:sort_by', :controller=> 'habitat_types', :action=>'index'
    match '/status/page/:page_no/sort/:sort_by', :controller=> 'statuses', :action=>'index'
    match '/skill/page/:page_no/sort/:sort_by', :controller=> 'skills', :action=>'index'
    match '/employee/page/:page_no/sort/:sort_by', :controller=> 'employees', :action=>'index'
    match '/maintenance/page/:page_no/sort/:sort_by', :controller=> 'maintenances', :action=>'index'
    match '/food/page/:page_no/sort/:sort_by', :controller=> 'foods', :action=>'index'
    match '/event/page/:page_no/sort/:sort_by', :controller=> 'events', :action=>'index'
    match '/performance/page/:page_no/sort/:sort_by', :controller=> 'performances', :action=>'index'
    match '/subscriber/page/:page_no/sort/:sort_by', :controller=> 'subscribers', :action=>'index'
    match '/buyer/page/:page_no/sort/:sort_by', :controller=> 'buyers', :action=>'index'
    match '/sponsor/page/:page_no/sort/:sort_by', :controller=> 'sponsors', :action=>'index'
    match '/adoption/page/:page_no/sort/:sort_by', :controller=> 'adoptions', :action=>'index'
    match '/sponsorship/page/:page_no/sort/:sort_by', :controller=> 'sponsorships', :action=>'index'
    match '/user/page/:page_no/sort/:sort_by', :controller=> 'users', :action=>'index'
    match '/post/page/:page_no/sort/:sort_by', :controller=> 'posts', :action=>'index'
    match '/comment/page/:page_no/sort/:sort_by', :controller=> 'comments', :action=>'index'
    match '/zoomap/page/:page_no/sort/:sort_by', :controller=> 'zoomaps', :action=>'index'
    match '/map_area/page/:page_no/sort/:sort_by', :controller=> 'map_areas', :action=>'index'

    resources :habitat_types,:habitats, :animals, :statuses, :skills, :employees, 
	:maintenances, :foods, :events, :performances, :subscribers, :buyers, :sponsors, :adoptions, 
	:sponsorships, :users, :posts, :comments, :zoomaps, :map_areas
  end

  match '/admin/:action', :controller=>'admin/admin_main' 
  match '/admin', :controller=> 'admin/admin_main', :action => 'index'

  match '/:action', :controller => 'global'
  match '/index/page/:page_no', :controller=> 'global', :action=>'index'
  match '/zoogle/:action', :controller=> 'global'
  match '/zoogle/:action/:id', :controller=> 'global'
  match '/:action/:event_date', :controller => 'global'
  
  match ':controller/:action/:id'
  match ':controller/:action/:id.:format'

  
end

app/models/sponsorship.rb
class Sponsorship < ActiveRecord::Base
  belongs_to :animal
  belongs_to :sponsor
  
  validates_presence_of :animal_id, :sponsor_id
  validates_uniqueness_of :animal_id
end

app/controllers/admin/sponsorships_controller.rb
class Admin::SponsorshipsController < Admin::AdminMainController

  before_filter :require_human_resource
  def index
    # pagination logic
	# count sponsorships
	sponsorship_count = Sponsorship.count
	
	@no_of_pages = (sponsorship_count % 10)== 0 ? sponsorship_count/10 : (sponsorship_count/10) + 1
	
	@current_page = params[:page_no] ? params[:page_no].to_i : 1
	
	@sort_by = params[:sort_by] ? params[:sort_by] : "id"
	
	@sponsorships = Sponsorship.find(:all, :offset =>(@current_page-1) * 10, :limit=> 10, :order=>"#{@sort_by}")
	
  end

  def show
    @sponsorship = Sponsorship.find(params[:id])
  end
  
  def new
    @sponsorship = Sponsorship.new
  end

  def create
    @sponsorship = Sponsorship.new(params[:sponsorship])
    if @sponsorship.save
      flash[:notice] = "Added new sponsorship."
      redirect_to admin_sponsorship_path(@sponsorship)
      
    else
      flash[:notice] = "Failed saving new sponsorship."
      render :action => "new"
    end
    
    
  end

  def edit
    @sponsorship = Sponsorship.find(params[:id])
  end

  def update
    @sponsorship = Sponsorship.find(params[:id])
    if @sponsorship.update_attributes(params[:sponsorship])
      flash[:notice] = "Updated sponsorship."
      redirect_to admin_sponsorship_path(@sponsorship)
      
    else
      flash[:notice] = "Failed updating sponsorship."
      render :action => "edit"
    end

  end

  def destroy
    @sponsorship = Sponsorship.find(params[:id])
    if @sponsorship.destroy
      flash[:notice] = "Deleted sponsorship."
      
    else
      flash[:notice] = "Failed deleting sponsorship."
    end
    redirect_to admin_sponsorships_path
  end

  private
	def require_human_resource
		unless ["Human Resource", "Administrator"].include? session[:employee_type]
			flash[:notice] = "Unauthorized access."
			redirect_to '/admin/management'
		end		
	end
end

app/helpers/sponsorships_helper.rb
module SponsorshipsHelper
end

app/views/admin/sponsorships/_form.erb
<%= form_for([:admin,@sponsorship]) do |f|%>
  <% if @sponsorship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sponsorship.errors.count, "error") %> prohibited this sponsorship from being saved:</h2>

      <ul>
      <% @sponsorship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p>
<%= f.label "Animal:" %></br> 
<%= f.collection_select :animal_id, Animal.find_by_sql("SELECT ANIMALS.* FROM ANIMALS LEFT OUTER JOIN SPONSORSHIPS ON ANIMALS.ID = SPONSORSHIPS.ANIMAL_ID WHERE SPONSOR_ID IS NULL ORDER BY ANIMALS.NAME") , :id, :name, :prompt =>"Select an animal" %>
</p>


<p>
<%= f.label "Sponsor:" %></br> 
<%= f.collection_select :sponsor_id, Sponsor.find(:all, :conditions=> "status = 'Active'"), :id, :name, :prompt =>"Select a sponsor" %>
</p>




<p>
<%= f.label "Sponsor date:" %></br> 
<%= f.date_select :sponsor_date %>
</p>


<p>
<%= f.submit button%>
</p>

app/views/admin/sponsorships/_list.html.erb
<table border="2" align="center" >
<tr class="table_head"><td><b><%= link_to "ID", "/admin/sponsorship/page/#{@current_page}/sort/id" %></b></td>
    <td><b>SPONSOR</b></td>
    <td><b>ANIMAL</b></td>
    <td><b>OPERATIONS</b></td>
</tr>
<% @sponsorships.each do |p| %>
<tr>
<td><%= p.id %></td>
<td><%= p.sponsor.name %> </td>
<td><%= p.animal.name %> </td>
<td>	<%= link_to "Show", admin_sponsorship_path(p) %>
	 <%= link_to "Edit", edit_admin_sponsorship_path(p) %>
         <%= link_to "Delete", admin_sponsorship_path(p), :confirm=>"Are you sure?",:method=>'delete' %>
</td>
</tr>
  <% end %>
</table>

app/views/admin/sponsorships/edit.html.erb
<h1>Edit Sponsorship</h1>

<%= render :partial=>'form', :locals=>{:button=>'Update'}%>

app/views/admin/sponsorships/index.html.erb
<h1>Sponsorship</h1>
<div class="post">
  <%= render :partial => 'list' %>
<%= link_to "New Sponsorship", new_admin_sponsorship_path %>

<% if @current_page > 1 %>
	<%= link_to "back", "/admin/sponsorship/page/#{@current_page-1}/sort/#{@sort_by}" %>
<% end %>

<% @no_of_pages.times do |page|%>
	<% unless page+1 == @current_page %>
		<%= link_to page+1, "/admin/sponsorship/page/#{page+1}/sort/#{@sort_by}" %>
	<% else %>
		<%= page+1 %>
	<% end %>
<% end %>

<% if @current_page < @no_of_pages %>
	<%= link_to "next", "/admin/sponsorship/page/#{@current_page+1}/sort/#{@sort_by}" %>
<% end %>

</div>

app/views/admin/sponsorships/new.html.erb
<h1>New Sponsorship</h1>

<%= render :partial=>'form', :locals=>{:button=>'Create'}%>

app/views/admin/sponsorships/show.html.erb
<h1>
<%=h @sponsorship.sponsor.name%> - <%=h @sponsorship.animal.name%><font size=2>&nbsp;[<%= link_to "Edit", edit_admin_sponsorship_path(@sponsorship) %>]</font></h1>

<div class="post">
<table id="shows" align="center">

<tr><td width="120">Sponsor Date: </td>
<td><%= @sponsorship.sponsor_date.strftime("%B %d, %Y, %A") %></td>
</tr>
<tr><td>Animal Sponsored: </td>
<td><%= link_to @sponsorship.animal.name, admin_animal_path(@sponsorship.animal) %></td>
</tr>
<tr><td>Sponsor:</td>
<td><%= link_to @sponsorship.sponsor.name, admin_sponsor_path(@sponsorship.sponsor)%></td>
</tr>
</table>
</div>